// <auto-generated />
using System;
using ConnectApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250712115917_user-post-relationship")]
    partial class userpostrelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectApp.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrOfReports")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Welcome to ConnectApp! This is your first post.",
                            DateCreated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            NrOfReports = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Content = "ConnectApp is designed to help you connect with others.",
                            DateCreated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            NrOfReports = 0,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "Feel free to explore and share your thoughts!",
                            DateCreated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            NrOfReports = 0,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("ConnectApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Ahmed Mahmoud",
                            ProfilePictureUrl = " "
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Youssef Mostafa",
                            ProfilePictureUrl = " "
                        });
                });

            modelBuilder.Entity("ConnectApp.Models.Post", b =>
                {
                    b.HasOne("ConnectApp.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConnectApp.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
