// <auto-generated />
using System;
using ConnectApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectApp.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NrOfReports")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Welcome to ConnectApp! This is your first post.",
                            DateCreated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            NrOfReports = 0
                        },
                        new
                        {
                            PostId = 2,
                            Content = "ConnectApp is designed to help you connect with others.",
                            DateCreated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            NrOfReports = 0
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Feel free to explore and share your thoughts!",
                            DateCreated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2025, 7, 12, 14, 34, 0, 0, DateTimeKind.Utc),
                            NrOfReports = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
